global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'premeierleague_stat'
    metrics_path: '/metrics'
    scheme: http
    static_configs:
      - targets: ['premierleague-data-exporter:8000']